apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: concourse
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: concourse
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: concourse
    helm:
      parameters:
      - name: web.service.api.type
        value: ClusterIP
    repoURL: https://concourse-charts.storage.googleapis.com
    targetRevision: 14.5.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true