apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeapps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kubeapps
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    chart: kubeapps
    helm:
      parameters:
        name: useHelm3
        value: true
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 5.0.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeapps-operator
  namespace: kubeapps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeapps-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeapps-operator
  namespace: kubeapps